services:

###############################
#                             #
#  Network and reverse proxy  #
#                             #
###############################
 
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    working_dir: /traefik
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "443:443"
      - "127.0.0.1:4001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - proxy
      - stack
    depends_on:
      dns-refresher:
        condition: service_healthy

  dns-refresher:
    container_name: dns-refresher
    restart: unless-stopped
    working_dir: /traefik
    build:
      context: ./traefik
      dockerfile: dockerfile/master.dockerfile
    volumes:
      - ./traefik/update-dns.sh:/app/update-dns.sh:ro
      - ./traefik/watcher.sh:/app/watcher.sh:ro
      - ./traefik/dns.env:/app/dns.env:ro
      - ./traefik/aws.env:/app/aws.env:ro
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    networks:
      - stack

  
###############################
#                             #
#  Network and reverse proxy  #
#                             #
###############################

networks:
  stack:
    external: true
  proxy:
    external: true

###############################
#                             #
#  Volumes                    #
#                             #
###############################

volumes:
  traefik_letsencrypt: