entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  metrics:
    address: ":8082"

log:
  level: "DEBUG"

api:
  dashboard: true
  insecure: true

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

providers:
  docker:
    network: proxy
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: "fluke128@gmx.de"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: route53
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
 