entryPoints:
  web:
    address: ":80"
    http:
      middlewares:
        - "crowdsec"
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      middlewares:
        - "crowdsec"

log:
  level: "DEBUG"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    network: proxy
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "fluke128@gmx.de"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: route53
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

experimental:
  plugins:
    crowdsec-bouncer-traefik-plugin:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.4.4"
 