entryPoints:
  websecure:
    address: ":443"

log:
  level: "DEBUG"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    network: proxy
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: "fluke128@gmx.de"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: route53
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
 