# Port mappings for monitoring stack:
# Grafana:       7001 (internal: 3000)
# Prometheus:    7002 (internal: 9090)
# Loki:          7003 (internal: 3100)
# Node-exporter: 7004 (internal: 9100)
# Promtail:      7005 (internal: 9080)

server:
  http_listen_port: 7005
  grpc_listen_port: 0

positions:
  filename: /data/positions.yaml

clients:
  - url: http://loki:7003/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/log/docker/*.log

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/syslog

  # Add additional scrape configs for your specific needs
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
