http:

  middlewares:
    preserve-xff:
      headers:
        customRequestHeaders:
          X-Original-Forwarded-For: "{{ .Request.Headers.X-Forwarded-For }}"

    crowdsec:
      plugin:
        bouncer:
          enabled: true
          crowdsecLapiKey: "NjOmsarLRT388yfmKKuHzviHQ04kzmLsg9lR7clSINI"
          crowdsecLapiScheme: http
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiPath: "/"
          metricsUpdateIntervalSeconds: 600
          forwardedHeadersEnabled: true
          forwardedHeadersNbip: 1
          trustXFF: true
          userAgentEnabled: true