apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:7002
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:7003
    isDefault: false
    editable: false
